### ISSUE TITLE
Suggest make style file can be configured via option or path

### ISSUE THREAD

**Issue by singlewind** [AllMightySauron/ascii-table3#10]

**Comment by AllMightySauron** [comment]
As far as I can understand you wanted something like a `loadStylesFromFile(filename)` method.

Is this correct?

**Comment by singlewind** [comment]
Something like a dot file will be great.

**Comment by AllMightySauron** [comment]
> Something like a dot file will be great.

Where would that dot file reside?

**Comment by AllMightySauron** [comment]
Closed due to lack of feedback
