### ISSUE TITLE
Emjoji count as 2

### ISSUE THREAD

**Issue by andrelec1** [AllMightySauron/ascii-table3#17]
I use it to display scoreboard with my discord bot :
![image](https://github.com/AllMightySauron/ascii-table3/assets/3273204/4b94b4a0-ee43-435f-8e95-c05eea2820df)

using this config : 
```js
 const table: AsciiTable3 = new AsciiTable3()
                .setHeading('#', 'User', 'Kiwi')
                .setAlign(1, AlignmentEnum.CENTER)
                .setAlign(2, AlignmentEnum.CENTER)
                .setAlign(3, AlignmentEnum.RIGHT)
                .addRowMatrix(results);
            table.setStyle('compact');
```

As you can see, the 3 first ligne isn't aligned with other ...

Emoji is count as 2, but it take 1 place when it render, so the algorithm add 1 extra space .

**Comment by AllMightySauron** [comment]
Hi, 

Unfortunately, emojis are typically not monospaced characters which makes formatting tables containing emoji a nightmare.

Take a look at the example below:

|aa|
|✔|
|⭐|
|🚫|
|🥇|

It doesn't look like there's much I can do about it.

Cheers
