### ISSUE TITLE
Off-center column hurts my OCD :/

### ISSUE THREAD

**Issue by Oliver-Turp** [AllMightySauron/ascii-table3#18]
I just noticed during testing that the middle column is slightly off center, despite having `.setAlignCenter(true)`

I'll attach the code and [an image](https://github.com/AllMightySauron/ascii-table3/assets/55669423/1228c823-a521-4bfa-a94a-542b3af3dd41) for reference :) 

Any advice would be great! 

```
const { updatePosition } = require("../../prisma/levelling/functions");
var { AsciiTable3 } = require("ascii-table3");

module.exports = {
  data: {
    name: "leaderboard",
    description: "View the XP leaderboard",
    type: 1,
  },
  async execute(interaction) {
    const leaderboardData = await updatePosition();

    if (leaderboardData) {
      // Create an ASCII table with compact style
      const table = new AsciiTable3("XP Leaderboard");
      table
        .setHeading("#", "XP", "User")
        .setAlignCenter(true)
        .setStyle("unicode-round");
      //  .setStyle("unicode-mix");
      // .setStyle("unicode-single")

      leaderboardData.forEach((entry, index) => {
        table.addRow(index + 1, entry.xp, entry.user.username);
      });

      // Send the table as a message in Discord
      await interaction.reply(`\`\`\`${table.toString()}\`\`\``);
    } else if (leaderboardData.length === 0) {
      await interaction.reply({
        content: "The leaderboard is empty...",
        ephemeral: true,
      });
    } else {
      await interaction.reply({
        content: "An error occurred while updating the leaderboard.",
        ephemeral: true,
      });
    }
  },
};
```

**Comment by AllMightySauron** [comment]
Which column do you want to center? Is it the heading or column data?

if you're talking about data, you must pass the column number to setAlignCenter().

Example: setAlignCenter(3) for the 3rd column.

**Comment by Oliver-Turp** [comment]
I did mean the data yes. If I wanted to set ALL columns to center, you're saying I need to pass all the column numbers individually?

**Comment by AllMightySauron** [comment]
I haven't created a method for that, but you can use `setAligns()` with an array of the desired alignments for each column.

Example: `setAligns([AlignmentEnum.CENTER, AlignmentEnum.CENTER, AlignmentEnum.CENTER])`
