### ISSUE TITLE
Ignore chars for width computation

### ISSUE THREAD

**Issue by luwol03** [AllMightySauron/ascii-table3#3]
Is it possible to exclude certain characters from the width computation? This is usefull if the table cells includes markdown syntax e.g. `**` that doesn't need to be included in the maxwidth of a column.

**Comment by AllMightySauron** [comment]
Can you give an example of what you're trying to accomplish?

**Comment by luwol03** [comment]
I have something like that:
```
~~Abc~~ def
Abc     def
``` so the table column gets unnecessary big width.

**Comment by AllMightySauron** [comment]
As far as I know, cell widths on markdown table can vary, as shown below. The rendered output will look the same.

| Syntax | Description |
| --- | ----------- |
| Header | Title |
| Paragraph | Text |

There's really no need for extra spaces

**Comment by luwol03** [comment]
I know, with pure markdown that doesn't make any sense, but I like to send discord messages with an ascii table, so the spaces are necessary, as there are no md tables.

**Comment by luwol03** [comment]
Just ignore the ~~. So expected:
Abc def
Abc def

**Comment by AllMightySauron** [comment]
So, your idea would be to pre-process any markdown syntax and strip text down to bare strings?

**Comment by luwol03** [comment]
Not strip out, just for the width conpution. Maybe we can add an option to blacklist chars for the max width compution so that the table doesn't get a unnecessary width.

**Comment by AllMightySauron** [comment]
ah, ok. It's clear now.

**Comment by AllMightySauron** [comment]
I've been trying to figure out how to cope with your request without breaking the entire package rendering logic.

I still don't get one thing: discord does not have a monospaced font for messages unless you use code blocks. How are you planning to align the table cells?

This table
```
| Abcd | Abcd |
|------|------|
| ~~abcd~~ | abcd |
```

gets rendered as
![image](https://user-images.githubusercontent.com/72256753/158981214-ebbc1bd0-ef80-473c-942a-490341978af3.png)

**Comment by luwol03** [comment]
Thank you very much for your effort. I planned ignoring that discord isn't using a monospaced font. If I don't use any table border my tests returned pretty good examples, there was just so much spacing after the first bold column.
![image](https://user-images.githubusercontent.com/60048565/159078975-ba3b9ad5-1b43-41cc-84ea-369a230b03ce.jpeg)

**Comment by AllMightySauron** [comment]
> Thank you very much for your effort. I planned ignoring that discord isn't using a monospaced font. If I don't use any table border my tests returned pretty good examples, there was just so much spacing after the first bold column. ![image](https://user-images.githubusercontent.com/60048565/159078975-ba3b9ad5-1b43-41cc-84ea-369a230b03ce.jpeg)

I think I have a working version in line with what we've discussed. Can you send me a test table so that I can verify if we have the expected output?

**Comment by AllMightySauron** [comment]
So, with a sample code like this (passes a new string length function for column sizing purposes):

```javascript
const { AsciiTable3 } = require('./ascii-table3');
const removeMd = require('remove-markdown');

function myStrlen(str) {
    return removeMd(str).length + 1;
}

const table = new AsciiTable3()
                .setStyle('none')
                .setCellMargin(0)
                .addRowMatrix([
                            ['-', '**M1**', 'abc', 'def'],
                            ['-', '**M2**', 'cba', 'fed'],
                            ['-', '**M3**', 'bac', 'edf'],
                            ['-', '**M10**', 'bac', 'edf'],
                            ['-', '**M999**', 'xyz', 'wwwd'],
                        ]);

console.log(table.toString(myStrlen));
```

this is what i'm getting:

```
- **M1**   abc def 
- **M2**   cba fed
- **M3**   bac edf
- **M10**  bac edf
- **M999** xyz wwwd
```

Again, since discord font is not monospace, it will start to get weird pretty soon:

![image](https://user-images.githubusercontent.com/72256753/159508266-a36326ea-b17e-4f59-b3c1-3b3b7b398d05.png)

**Comment by luwol03** [comment]
Pretty cool. How can I test that? Is that already in the main branch or do I need to checkout a specific ref?

**Comment by AllMightySauron** [comment]
I have created a new branch called `md-special`. Are you using git or npm?

**Comment by luwol03** [comment]
For now it doesn't mind. I can install it both ways. Are you planning to merge this if its tested?

**Comment by AllMightySauron** [comment]
That's the idea. Give me some feedback as soon as you test it...

**Comment by luwol03** [comment]
Sorry to tell you, but adding such a function doesnt change anything. Everytime the same output. 
```js
const table = new AsciiTable3()
  .setStyle('none')
  .setCellMargin(0)
  .addRowMatrix([
    ['-', '**M1**', 'abc', 'def'],
    ['-', '**M2**', 'cba', 'fed'],
    ['-', '**M3**', 'bac', 'edf'],
    ['-', '**M10**', 'bac', 'edf'],
    ['-', '**M999**', 'xyz', 'wwwd'],
  ]);

console.log(table.toString())
console.log(table.toString((s) => s.length + 10))
console.log(table.toString((s) => s.length + 10) === table.toString())
```

Now it came into my mind, that this can also used for ANSI escape sequences, so that the table there doesnt get to big.

**Comment by AllMightySauron** [comment]
You need a function that calculates string length **after** removing markdown...

Please take a look at my example above.

**Comment by luwol03** [comment]
I know, but that doesnt worked, so I tried to do that static. In theory I could easily add 10 spaces. But that doesn't work.

**Comment by luwol03** [comment]
Is this now implemented?
