### ISSUE TITLE
one line breaks by emoji

### ISSUE THREAD

**Issue by VidarDev** [AllMightySauron/ascii-table3#4]
![ascii](https://user-images.githubusercontent.com/98586665/159114769-1ccecd9a-4db6-42c8-afea-a592be403ae0.png)

**Comment by AllMightySauron** [comment]
Hi, that seems to be an upstream issue. Most likely, your font is not using monospaced characters for emojis (that rocket seems to be taking 2 or more columns)

If that is the case, there's nothing I can do...

**Comment by VidarDev** [comment]
> Hi, that seems to be an upstream issue. Most likely, your font is not using monospaced characters for emojis (that rocket seems to be taking 2 or more columns)
> 
> If that is the case, there's nothing I can do...
> 
> I can confirm the size considered for this unicode char is: ![image](https://user-images.githubusercontent.com/72256753/159295459-41f007a4-bda1-4edc-a7da-36acd69f2245.png)

ah ok check yes now understand thats my font^^
