### ISSUE TITLE
OS License

### ISSUE THREAD

**Issue by kvandelden** [AllMightySauron/ascii-table3#5]
Any chance you would consider licensing this under Apache 2 or MIT OS licenses?
  We are using ascii-table in a console utility.  Upon review by a client's legal department, they are asking us to remove it.  I'd rather not..

Thanks for writing this library,
Kurt

**Comment by AllMightySauron** [comment]
Hi Kurt, I see no problem in that. Let me make those changes in the upcoming version.

BWT, out of curiosity, what are you doing with this package? :)

**Comment by kvandelden** [comment]
We have console tools that help us maintain all of our database artifacts, ( tables, views, metadata, etc)  in GIT..  The metadata manager tool allows our developers to import table records into metadata files, and have the metadata created when a deployment is run.  The ascii table library makes the UI nicer, and the code cleaner by separating out the nuanced presentation logic from the metadata management logic.  
Thanks!
