### ISSUE TITLE
Make this package usable in browser

### ISSUE THREAD

**Issue by phatNfqAsia** [AllMightySauron/ascii-table3#6]
Hi I found this code lines is not necessary while preventing this package from being used in browser context
https://github.com/AllMightySauron/ascii-table3/blob/main/ascii-table3.js#L28
https://github.com/AllMightySauron/ascii-table3/blob/main/ascii-table3.js#L42

You can do this for a more straightforward approach

```javascript
this.styles = require('./ascii-table3.styles.json');
```

**Comment by AllMightySauron** [comment]
Hi, I'm afraid it will stop working as a module inside NodeJS if I use your approach due to the relative paths no being met...

Can you provide me with a test case for the browers so that I can change the code and verify both approaches work?

**Comment by phatNfqAsia** [comment]
@AllMightySauron let me find a way to do it because I have not known how to change runtime context in testing :grin:

**Comment by AllMightySauron** [comment]
closed due to inactivity...
